# Generated by Django 4.2.4 on 2023-09-01 15:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Appointment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="Name")),
                ("phone", models.CharField(max_length=10, verbose_name="Phone number")),
                (
                    "email",
                    models.TextField(max_length=50, verbose_name="Email address"),
                ),
                (
                    "problem",
                    models.TextField(max_length=300, verbose_name="Problem text"),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="post",
            name="content",
            field=models.TextField(verbose_name="Content"),
        ),
        migrations.AlterField(
            model_name="post",
            name="publish",
            field=models.BooleanField(default=False, verbose_name="Status"),
        ),
        migrations.AlterField(
            model_name="post",
            name="title",
            field=models.CharField(max_length=200, verbose_name="Title"),
        ),
        migrations.AlterField(
            model_name="review",
            name="content",
            field=models.TextField(max_length=300, verbose_name="Review text"),
        ),
        migrations.AlterField(
            model_name="review",
            name="grade",
            field=models.IntegerField(default=5, verbose_name="Grade"),
        ),
        migrations.AlterField(
            model_name="review",
            name="name",
            field=models.CharField(max_length=50, verbose_name="Name"),
        ),
        migrations.AlterField(
            model_name="review",
            name="phone",
            field=models.CharField(max_length=10, verbose_name="Phone number"),
        ),
        migrations.AlterField(
            model_name="review",
            name="publish",
            field=models.BooleanField(default=False, verbose_name="Status"),
        ),
    ]
